services:
  postgres:
    image: postgres:17
    container_name: postgres_db_test
    restart: always
    environment:
      POSTGRES_DB_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events
    ports:
      - "5433:5433"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data: