// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID          uuid.UUID
	Title       string
	Description *string
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}
